---
title: "Create the PM2.5 dataframe from 2000 to 2018"
author: "Yunlin Zhou"
date: "2023-03-05"
output: html_document
---

```{r setup, include=FALSE}
library(ncdf4) # package for netcdf manipulation
library(tidyverse)
```

# Read the .nc files

```{r}
# Set the directory containing the .nc files
setwd("./nc files")

# Get a list of all the .nc files in the directory
nc_files <- list.files(pattern = "*.nc")

# Loop through each .nc file and generate a table from the array
tables <- lapply(nc_files, function(file) {
  
  # Open the .nc file
  nc <- nc_open(file)
  
  # Extract the array and add row and column names
  array <- ncvar_get(nc, "PM25")
  rownames(array) <- ncvar_get(nc, "LON")
  colnames(array) <- ncvar_get(nc, "LAT")
  
  # Convert the array into a table with 3 columns
  table <- melt(array, varnames = c("lon", "lat"), value.name = paste("PM2.5 in", substr(file, 1, 4)))
  
  # Close the .nc file
  nc_close(nc)
  
  # Return the resulting table
  return(table)
})
```

# Extract the PM2.5 data frames from the list

```{r}
for (i in seq_along(tables)) {
  table_name <- paste0("PM25_table", as.character(i + 1999) )
  assign(table_name, as.data.frame(tables[[i]]))
}
```

# Merge the PM2.5 data frames into 1

```{r}
years <- c(2000:2018)

# create an empty data frame to store the results
PM25_df <- data.frame()

# loop through the years and left join the corresponding table to the existing data frame
for (year in years) {
  table_name <- paste0("PM25_table", year)
  table <- get(table_name)
  if (nrow(PM25_df) == 0) {
    PM25_df <- table
  } else {
    PM25_df <- left_join(PM25_df, table, by = c("lon", "lat"))
  }
}
```
